# Generated by Django 4.2.3 on 2023-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('descrition', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
